name: BuildJS
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'

    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install
      run: npm ci

    - name: Build
      run: npm run dist

    - name: Test
      run: npm run test:ci

    - name: Build container
      run: |
        npm run build
        BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")
        docker build . -t jeffriggle/robit:"$GITHUB_SHA"
        docker build . -t jeffriggle/robit:"${BRANCH}"

    - name: Publish
      env:
        dockerpassword: ${{ secrets.DOCKER }}
        dockeruser: ${{ secrets.DOCKERUSER }}
      run: |
        BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")
        docker login -p $dockerpassword -u $dockeruser
        docker push jeffriggle/robit:"$GITHUB_SHA"
        docker push jeffriggle/robit:"${BRANCH}"